<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Model</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentSettings.Generator" />
    <PackageReference Include="LiteDB" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
