<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Utilities</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiteDB" />
    <PackageReference Include="Mastonet" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
