using System.Text.Json.Serialization;

namespace Model.Server;

[JsonSerializable(typeof(Entities.AccountWarning))]
[JsonSerializable(typeof(Entities.Account))]
[JsonSerializable(typeof(Entities.Appeal))]
[JsonSerializable(typeof(Entities.AdminAccount))]
[JsonSerializable(typeof(Entities.AdminIp))]
[JsonSerializable(typeof(Entities.Announcement))]
[JsonSerializable(typeof(Entities.Application))]
[JsonSerializable(typeof(Entities.Collection))]
[JsonSerializable(typeof(Entities.CollectionItem))]
[JsonSerializable(typeof(Entities.CollectionWithAccounts))]
[JsonSerializable(typeof(Entities.Collections))]
[JsonSerializable(typeof(Entities.Context))]
[JsonSerializable(typeof(Entities.Conversation))]
[JsonSerializable(typeof(Entities.CustomEmoji))]
[JsonSerializable(typeof(Entities.Error))]
[JsonSerializable(typeof(Entities.FamiliarFollowers))]
[JsonSerializable(typeof(Entities.FeatureApproval))]
[JsonSerializable(typeof(Entities.FeaturedTag))]
[JsonSerializable(typeof(Entities.Filter))]
[JsonSerializable(typeof(Entities.FilterKeyword))]
[JsonSerializable(typeof(Entities.FilterResult))]
[JsonSerializable(typeof(Entities.FilterStatus))]
[JsonSerializable(typeof(Entities.IdentityProof))]
[JsonSerializable(typeof(Entities.Instance))]
[JsonSerializable(typeof(Entities.List))]
[JsonSerializable(typeof(Entities.Marker))]
[JsonSerializable(typeof(Entities.MediaAttachment))]
[JsonSerializable(typeof(Entities.Notification))]
[JsonSerializable(typeof(Entities.NotificationFallback))]
[JsonSerializable(typeof(Entities.Poll))]
[JsonSerializable(typeof(Entities.Preferences))]
[JsonSerializable(typeof(Entities.PreviewCard))]
[JsonSerializable(typeof(Entities.PreviewCardAuthor))]
[JsonSerializable(typeof(Entities.Suggestion))]
[JsonSerializable(typeof(Entities.Quote))]
[JsonSerializable(typeof(Entities.QuoteApproval))]
[JsonSerializable(typeof(Entities.Reaction))]
[JsonSerializable(typeof(Entities.Relationship))]
[JsonSerializable(typeof(Entities.RelationshipSeveranceEvent))]
[JsonSerializable(typeof(Entities.Report))]
[JsonSerializable(typeof(Entities.Role))]
[JsonSerializable(typeof(Entities.Rule))]
[JsonSerializable(typeof(Entities.ScheduledStatus))]
[JsonSerializable(typeof(Entities.Search))]
[JsonSerializable(typeof(Entities.ShallowTag))]
[JsonSerializable(typeof(Entities.Status))]
[JsonSerializable(typeof(Entities.Tag))]
[JsonSerializable(typeof(Entities.Token))]
[JsonSerializable(typeof(Methods.HealthStatus))]
[JsonSerializable(typeof(Methods.Markers))]
[JsonSerializable(typeof(Methods.NotificationRequestsMerged))]
[JsonSerializable(typeof(Methods.NotificationUnreadCount))]
[JsonSerializable(typeof(Methods.OAuthServerConfiguration))]
[JsonSerializable(typeof(Methods.OEmbed))]
[JsonSerializable(typeof(Methods.ProofResponse))]
[JsonSerializable(typeof(Methods.SearchV1))]
[JsonSerializable(typeof(Methods.UserInfo))]
[JsonSerializable(typeof(Methods.WeeklyActivity))]
[JsonSourceGenerationOptions(UseStringEnumConverter = true)]
public partial class JsonContext: JsonSerializerContext {
}
