using Model.Server.Entities;
using System.Text.Json.Serialization;

namespace Model.Server;

[JsonSerializable(typeof(Account))]
[JsonSerializable(typeof(MutedAccount))]
[JsonSerializable(typeof(CredentialAccount))]
[JsonSerializable(typeof(PartialAccountWithAvatar))]
[JsonSerializable(typeof(AccountRole))]
[JsonSerializable(typeof(Field))]
[JsonSerializable(typeof(AdminAccount))]
[JsonSerializable(typeof(AdminIp))]
[JsonSerializable(typeof(Announcement))]
[JsonSerializable(typeof(Application))]
[JsonSerializable(typeof(Collection))]
[JsonSerializable(typeof(Context))]
[JsonSerializable(typeof(Conversation))]
[JsonSerializable(typeof(CustomEmoji))]
[JsonSerializable(typeof(Error))]
[JsonSerializable(typeof(FeatureApproval))]
[JsonSerializable(typeof(FeaturedTag))]
[JsonSerializable(typeof(Filter))]
[JsonSerializable(typeof(FilterKeyword))]
[JsonSerializable(typeof(FilterResult))]
[JsonSerializable(typeof(FilterStatus))]
[JsonSerializable(typeof(IdentityProof))]
[JsonSerializable(typeof(Instance))]
[JsonSerializable(typeof(List))]
[JsonSerializable(typeof(MediaAttachment))]
[JsonSerializable(typeof(Notification))]
[JsonSerializable(typeof(Poll))]
[JsonSerializable(typeof(PollOption))]
[JsonSerializable(typeof(PollParameters))]
[JsonSerializable(typeof(PreviewCard))]
[JsonSerializable(typeof(PreviewCardAuthor))]
[JsonSerializable(typeof(Quote))]
[JsonSerializable(typeof(QuoteApproval))]
[JsonSerializable(typeof(Reaction))]
[JsonSerializable(typeof(Relationship))]
[JsonSerializable(typeof(Report))]
[JsonSerializable(typeof(Role))]
[JsonSerializable(typeof(Rule))]
[JsonSerializable(typeof(ScheduledStatus))]
[JsonSerializable(typeof(Search))]
[JsonSerializable(typeof(ShallowTag))]
[JsonSerializable(typeof(Status))]
[JsonSerializable(typeof(Tag))]
[JsonSerializable(typeof(AdminTag))]
[JsonSerializable(typeof(Token))]
[JsonSourceGenerationOptions(UseStringEnumConverter = true)]
public partial class JsonContext: JsonSerializerContext
{
}