using System.Text.Json.Serialization;

namespace Model.Server;

[JsonSerializable(typeof(Entities.Admin.Account), TypeInfoPropertyName = "Admin_Account")]
[JsonSerializable(typeof(Entities.Admin.CanonicalEmailBlock), TypeInfoPropertyName = "Admin_CanonicalEmailBlock")]
[JsonSerializable(typeof(Entities.Admin.Cohort), TypeInfoPropertyName = "Admin_Cohort")]
[JsonSerializable(typeof(Entities.Admin.CohortData), TypeInfoPropertyName = "Admin_CohortData")]
[JsonSerializable(typeof(Entities.Admin.CohortFrequency), TypeInfoPropertyName = "Admin_CohortFrequency")]
[JsonSerializable(typeof(Entities.Admin.Dimension), TypeInfoPropertyName = "Admin_Dimension")]
[JsonSerializable(typeof(Entities.Admin.DimensionData), TypeInfoPropertyName = "Admin_DimensionData")]
[JsonSerializable(typeof(Entities.Admin.DomainAllow), TypeInfoPropertyName = "Admin_DomainAllow")]
[JsonSerializable(typeof(Entities.Admin.DomainBlock), TypeInfoPropertyName = "Admin_DomainBlock")]
[JsonSerializable(typeof(Entities.Admin.DomainBlockSeverity), TypeInfoPropertyName = "Admin_DomainBlockSeverity")]
[JsonSerializable(typeof(Entities.Admin.EmailDomainBlock), TypeInfoPropertyName = "Admin_EmailDomainBlock")]
[JsonSerializable(typeof(Entities.Admin.EmailDomainBlockHistory), TypeInfoPropertyName = "Admin_EmailDomainBlockHistory")]
[JsonSerializable(typeof(Entities.Admin.Ip), TypeInfoPropertyName = "Admin_Ip")]
[JsonSerializable(typeof(Entities.Admin.IpBlock), TypeInfoPropertyName = "Admin_IpBlock")]
[JsonSerializable(typeof(Entities.Admin.IpBlockSeverity), TypeInfoPropertyName = "Admin_IpBlockSeverity")]
[JsonSerializable(typeof(Entities.Admin.Measure), TypeInfoPropertyName = "Admin_Measure")]
[JsonSerializable(typeof(Entities.Admin.MeasureData), TypeInfoPropertyName = "Admin_MeasureData")]
[JsonSerializable(typeof(Entities.Admin.Report), TypeInfoPropertyName = "Admin_Report")]
[JsonSerializable(typeof(Entities.Admin.ReportCategory), TypeInfoPropertyName = "Admin_ReportCategory")]

[JsonSerializable(typeof(Entities.Account))]
[JsonSerializable(typeof(Entities.AccountWarning))]
[JsonSerializable(typeof(Entities.Announcement))]
[JsonSerializable(typeof(Entities.AnnualReport))]
[JsonSerializable(typeof(Entities.Appeal))]
[JsonSerializable(typeof(Entities.Application))]
[JsonSerializable(typeof(Entities.AsyncRefresh))]
[JsonSerializable(typeof(Entities.Collection))]
[JsonSerializable(typeof(Entities.CollectionItem))]
[JsonSerializable(typeof(Entities.CollectionWithAccounts))]
[JsonSerializable(typeof(Entities.Context))]
[JsonSerializable(typeof(Entities.Conversation))]
[JsonSerializable(typeof(Entities.CustomEmoji))]
[JsonSerializable(typeof(Entities.DomainBlock))]
[JsonSerializable(typeof(Entities.Error))]
[JsonSerializable(typeof(Entities.ExtendedDescription))]
[JsonSerializable(typeof(Entities.FamiliarFollowers))]
[JsonSerializable(typeof(Entities.FeatureApproval))]
[JsonSerializable(typeof(Entities.FeaturedTag))]
[JsonSerializable(typeof(Entities.Filter))]
[JsonSerializable(typeof(Entities.FilterKeyword))]
[JsonSerializable(typeof(Entities.FilterResult))]
[JsonSerializable(typeof(Entities.FilterStatus))]
[JsonSerializable(typeof(Entities.IdentityProof))]
[JsonSerializable(typeof(Entities.Instance))]
[JsonSerializable(typeof(Entities.List))]
[JsonSerializable(typeof(Entities.Marker))]
[JsonSerializable(typeof(Entities.MediaAttachment))]
[JsonSerializable(typeof(Entities.Notification))]
[JsonSerializable(typeof(Entities.NotificationFallback))]
[JsonSerializable(typeof(Entities.NotificationPolicy))]
[JsonSerializable(typeof(Entities.NotificationRequest))]
[JsonSerializable(typeof(Entities.Poll))]
[JsonSerializable(typeof(Entities.Preferences))]
[JsonSerializable(typeof(Entities.PreviewCard))]
[JsonSerializable(typeof(Entities.PreviewCardAuthor))]
[JsonSerializable(typeof(Entities.PrivacyPolicy))]
[JsonSerializable(typeof(Entities.Profile))]
[JsonSerializable(typeof(Entities.Quote))]
[JsonSerializable(typeof(Entities.QuoteApproval))]
[JsonSerializable(typeof(Entities.Reaction))]
[JsonSerializable(typeof(Entities.Relationship))]
[JsonSerializable(typeof(Entities.RelationshipSeveranceEvent))]
[JsonSerializable(typeof(Entities.Report))]
[JsonSerializable(typeof(Entities.Role))]
[JsonSerializable(typeof(Entities.Rule))]
[JsonSerializable(typeof(Entities.ScheduledStatus))]
[JsonSerializable(typeof(Entities.Search))]
[JsonSerializable(typeof(Entities.ShallowQuote))]
[JsonSerializable(typeof(Entities.ShallowTag))]
[JsonSerializable(typeof(Entities.Status))]
[JsonSerializable(typeof(Entities.StatusEdit))]
[JsonSerializable(typeof(Entities.StatusSource))]
[JsonSerializable(typeof(Entities.Suggestion))]
[JsonSerializable(typeof(Entities.Tag))]
[JsonSerializable(typeof(Entities.TermsOfService))]
[JsonSerializable(typeof(Entities.Token))]
[JsonSerializable(typeof(Entities.Translation))]
[JsonSerializable(typeof(Entities.V1Filter))]
[JsonSerializable(typeof(Entities.V1Instance))]
[JsonSerializable(typeof(Entities.V1NotificationPolicy))]
[JsonSerializable(typeof(Entities.WebPushSubscription))]

[JsonSerializable(typeof(Methods.HealthStatus))]
[JsonSerializable(typeof(Methods.Markers))]
[JsonSerializable(typeof(Methods.NotificationRequestsMerged))]
[JsonSerializable(typeof(Methods.NotificationUnreadCount))]
[JsonSerializable(typeof(Methods.OAuthServerConfiguration))]
[JsonSerializable(typeof(Methods.OEmbed))]
[JsonSerializable(typeof(Methods.ProofResponse))]
[JsonSerializable(typeof(Methods.SearchV1))]
[JsonSerializable(typeof(Methods.UserInfo))]
[JsonSerializable(typeof(Methods.WeeklyActivity))]
[JsonSourceGenerationOptions(UseStringEnumConverter = true)]
public partial class JsonContext: JsonSerializerContext {
}
